# Configuration File

# If true, everyone will be able to enchant any item with any enchantment possible
allow-unsafe-enchantments: false
# default: false

# If true, the enchantments will be able to be stacked, like in an anvil
# Ex: Protection 1 + Protection 1 = Protection 2
enchantments-can-be-stacked: true
# default: true


