name: InventoryBookEnchanter
version: '1.0'
main: me.lucasggmoreira.inventoryClickEnchanter.MainClass
api-version: '1.20'
commands:
  ibe:
    description: This is the core command of the plugin!
    usage: /<command>
    aliases: [inventorybookenchanter]
    permission: ibe.bookCommand

